version = 1
SPDX-PackageName = "btp-process-orchestration-migration-guide"
SPDX-PackageSupplier = "Melanie Cueppers (melanie.cueppers@sap.com)"
SPDX-PackageDownloadLocation = "https://github.com/SAP-docs/btp-process-orchestration-migration-guide"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022-2023 SAP SE or an SAP affiliate company and btp-process-orchestration-migration-guide contributors"
SPDX-License-Identifier = "CC-BY-4.0"
